version: '2.2'

services:
  db:
    image: 'postgres'
    ports:
      - '4321:5432'
    environment:
      POSTGRES_PASSWORD: '12345678'
      POSTGRES_USER: 'docker' 

  server:
    build: .
    ports:
      - '5000:5000'
